### PR TITLE
Added Material You switches in settings

### PR DESCRIPTION
**Pull request by GustavoASantos**

### CODE REVIEW

**Comment by GustavoASantos** [comment]
No, there isn't an official way yet as far as I'm aware. This is just what I am doing for now to match Google's look. I understand that, do you want me to close the pr?

**Comment by UweTrottmann** [comment]
Wait, I just checked the settings screens and they already use the new color scheme and style. What device or Android version did you use to test this?

image

**Comment by GustavoASantos** [comment]
You're right but that's not how it was looking to me, I must've changed something and made it wrong. Sorry about that. I used a Pixel 6. Give me a couple of days and I'll get back to you on this

**Comment by GeoZac** [comment]
I think the issue being "tried" to be addressed is [this](https://stackoverflow.com/questions/71456884/recreate-switches-similar-to-android-12-settings)
Settings app in android 12 has a distinct set of switch widgets available from the framework(provided by SettingsLib package)

**Comment by UweTrottmann** [comment]
@GeoZac Ah, thanks. So won't accept this PR then. Will stick with the style from the official Material Design Components library for Android.

**Pull request closed without merging**
