### PR TITLE
More description about your app

### PR DESCRIPTION
**Pull request by singhvaibhav06**
Nope it is compatible

### CODE REVIEW

**Comment by JakeWharton** [comment]
This is Hacktoberfest spam. Follow these steps https://hacktoberfest.digitalocean.com/details#spam to disqualify the user.

**Comment by singhvaibhav06** [comment]
I know that the changes are small but that doesn't mean that it is worthless. Sometimes small changes give a deeper impact. Helping community is my only priority.That's it.

**Comment by UweTrottmann** [comment]
@JakeWharton Thanks! How did you know?

@singhvaibhav06 Nice try!

**Comment by JakeWharton** [comment]
I'm used to seeing it every year, although this year seems worse than most.

- https://blog.domenic.me/hacktoberfest/
- https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama

**Pull request closed without merging**
